project:
  type: website
  output-dir: docs

website:
  title: "Îlots de Fraîcheur à Paris"
  navbar:
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Analyse"
        href: analyse.qmd
      - text: "Visualisations"
        href: visualisations.qmd
    right:
      - icon: github
        href: https://github.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
